In [1]:
%matplotlib inline

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
#Imported 4 sets of data
wine_file_red = "red_wine_0to400_anyrating.csv"
wine_file_sparkling = "sparkling_wine_0to400_anyrating.csv"
wine_file_white = "white_wine_0to400_anyrating (1).csv"
wine_file = "winemag-data-130k-v2.csv"
wine_file_df = pd.read_csv(wine_file)
wine_file_red_df = pd.read_csv(wine_file_red)
wine_file_sparkling_df = pd.read_csv(wine_file_sparkling)
wine_file_white_df = pd.read_csv(wine_file_white)
wine_file_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [5]:
# merged red&white&sparkling and dropped NA values and got rid of Unnamed 0
merged_df = wine_file_red_df.append(wine_file_white_df)
merged_df_1 = merged_df.append(wine_file_sparkling_df)
merged_df_1

,Unnamed: 0,Name,Rating,Price,NumberOfRatings,Country,Winery
0,0,Cobos Marchiori Vineyard Malbec 2015,4.8,$223.99,669 ratings,Argentina,Viña Cobos
1,1,Adrianna Vineyard River Stones Malbec 2015,4.8,$173.99,190 ratings,Argentina,Catena Zapata
2,2,Darius II Cabernet Sauvignon 2016,4.8,$324.99,104 ratings,United States,Darioush
3,3,Saint-Émilion Grand Cru 2014,4.8,$183.99,98 ratings,France,Château Tertre Roteboeuf
4,4,Fortis Cabernet Sauvignon 2014,4.8,$299.99,91 ratings,United States,Pine Ridge
...,...,...,...,...,...,...,...
1961,1961,La Grande Année Brut Champagne 2004,4.5,View shops,3097 ratings,France,Bollinger
1962,1962,Brut Champagne 2005,4.5,View shops,2981 ratings,France,Dom Pérignon
1963,1963,La Grande Dame Brut Champagne 2006,4.5,View shops,2689 ratings,France,Veuve Clicquot
1964,1964,La Grande Dame Brut Champagne 2004,4.5,View shops,2338 ratings,France,Veuve Clicquot
1965,1965,J. Schram Brut 2000,4.6,View shops,25 ratings,United States,Schramsberg

In [6]:
merged_df_2 = merged_df_1.drop(['Unnamed: 0'], axis=1)
merged_df_2

,Name,Rating,Price,NumberOfRatings,Country,Winery
0,Cobos Marchiori Vineyard Malbec 2015,4.8,$223.99,669 ratings,Argentina,Viña Cobos
1,Adrianna Vineyard River Stones Malbec 2015,4.8,$173.99,190 ratings,Argentina,Catena Zapata
2,Darius II Cabernet Sauvignon 2016,4.8,$324.99,104 ratings,United States,Darioush
3,Saint-Émilion Grand Cru 2014,4.8,$183.99,98 ratings,France,Château Tertre Roteboeuf
4,Fortis Cabernet Sauvignon 2014,4.8,$299.99,91 ratings,United States,Pine Ridge
...,...,...,...,...,...,...
1961,La Grande Année Brut Champagne 2004,4.5,View shops,3097 ratings,France,Bollinger
1962,Brut Champagne 2005,4.5,View shops,2981 ratings,France,Dom Pérignon
1963,La Grande Dame Brut Champagne 2006,4.5,View shops,2689 ratings,France,Veuve Clicquot
1964,La Grande Dame Brut Champagne 2004,4.5,View shops,2338 ratings,France,Veuve Clicquot
1965,J. Schram Brut 2000,4.6,View shops,25 ratings,United States,Schramsberg

In [7]:
merged_df_3 = merged_df_2.dropna()
merged_df_3.head()

,Name,Rating,Price,NumberOfRatings,Country,Winery
0,Cobos Marchiori Vineyard Malbec 2015,4.8,$223.99,669 ratings,Argentina,Viña Cobos
1,Adrianna Vineyard River Stones Malbec 2015,4.8,$173.99,190 ratings,Argentina,Catena Zapata
2,Darius II Cabernet Sauvignon 2016,4.8,$324.99,104 ratings,United States,Darioush
3,Saint-Émilion Grand Cru 2014,4.8,$183.99,98 ratings,France,Château Tertre Roteboeuf
4,Fortis Cabernet Sauvignon 2014,4.8,$299.99,91 ratings,United States,Pine Ridge

In [8]:
# removed unnamed column and replaced United States with US
merged_df_3["Country"]= merged_df_3["Country"].replace("United States", "US")
merged_df_3

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Name,Rating,Price,NumberOfRatings,Country,Winery
0,Cobos Marchiori Vineyard Malbec 2015,4.8,$223.99,669 ratings,Argentina,Viña Cobos
1,Adrianna Vineyard River Stones Malbec 2015,4.8,$173.99,190 ratings,Argentina,Catena Zapata
2,Darius II Cabernet Sauvignon 2016,4.8,$324.99,104 ratings,US,Darioush
3,Saint-Émilion Grand Cru 2014,4.8,$183.99,98 ratings,France,Château Tertre Roteboeuf
4,Fortis Cabernet Sauvignon 2014,4.8,$299.99,91 ratings,US,Pine Ridge
...,...,...,...,...,...,...
1961,La Grande Année Brut Champagne 2004,4.5,View shops,3097 ratings,France,Bollinger
1962,Brut Champagne 2005,4.5,View shops,2981 ratings,France,Dom Pérignon
1963,La Grande Dame Brut Champagne 2006,4.5,View shops,2689 ratings,France,Veuve Clicquot
1964,La Grande Dame Brut Champagne 2004,4.5,View shops,2338 ratings,France,Veuve Clicquot
1965,J. Schram Brut 2000,4.6,View shops,25 ratings,US,Schramsberg

In [ ]:
# Group by country, vivino data is rated out of 5 while the winespector data is rated out of 100